export type SunRequirement = 'full' | 'partial' | 'shade';
export type WaterRequirement = 'low' | 'medium' | 'high';

export interface Plant {
  slug: string;
  name: string;
  nameSv: string;
  family: string;
  plantsPerSquare: number; // how many fit in one 30x30cm square
  sunRequirement: SunRequirement;
  waterRequirement: WaterRequirement;
  daysToHarvest: number;
  description: string;
  tips: string;
  emoji: string;
  tags: string[];
}

export const PLANTS: Plant[] = [
  {
    slug: 'tomato',
    name: 'Tomato',
    nameSv: 'Tomat',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 70,
    description: 'Trädgårdens stapelvara. Behöver full sol och jämn vattning. Bind upp eller använd bur som stöd.',
    tips: 'Tjuva sidoskotten för större frukter. Vattna djupt men sällan.',
    emoji: '🍅',
    tags: ['grönsak', 'värmekrävande', 'behöver stöd'],
  },
  {
    slug: 'basil',
    name: 'Basil',
    nameSv: 'Basilika',
    family: 'Lamiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 25,
    description: 'Aromatisk ört som trivs i värme. Utmärkt sällskapsväxt till tomater.',
    tips: 'Nyp av blomknoppar så fortsätter bladen komma. Skörda på morgonen för bästa smak.',
    emoji: '🌿',
    tags: ['ört', 'värmekrävande'],
  },
  {
    slug: 'carrot',
    name: 'Carrot',
    nameSv: 'Morot',
    family: 'Apiaceae',
    plantsPerSquare: 16,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 75,
    description: 'Knaprig rotgrönsak. Direktså i djup, lucker jord. Gallra till 5 cm mellan plantorna.',
    tips: 'Luckra jorden till 30 cm djup. Undvik färsk gödsel — ger grenade rötter.',
    emoji: '🥕',
    tags: ['grönsak', 'rotfrukt', 'sval säsong'],
  },
  {
    slug: 'onion',
    name: 'Onion',
    nameSv: 'Lök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 100,
    description: 'Långsamväxande lökgrönsak. Plantera sättlök eller småplantor tidigt på våren.',
    tips: 'När bladen lägger sig ned är löken mogen. Torka 2–3 veckor på torr plats före lagring.',
    emoji: '🧅',
    tags: ['grönsak', 'lökväxt', 'sval säsong'],
  },
  {
    slug: 'garlic',
    name: 'Garlic',
    nameSv: 'Vitlök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 240,
    description: 'Sätt klyftorna på hösten för sommarens skörd. Utmärkt naturligt skadedjursskydd.',
    tips: 'Bryt av blomstängeln när den krullar för att styra energin till knölen. Skörda när halva bladverket är brunt.',
    emoji: '🧄',
    tags: ['grönsak', 'lökväxt', 'övervintrande'],
  },
  {
    slug: 'lettuce',
    name: 'Lettuce',
    nameSv: 'Sallat',
    family: 'Asteraceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 45,
    description: 'Snabbväxande salladsgrönt. Klarar lätt skugga och svalt väder. Skottresistenta sorter håller längre.',
    tips: 'Skörda ytterbladen så fortsätter plantan att producera. Så successivt varannan vecka.',
    emoji: '🥬',
    tags: ['grönsak', 'sval säsong', 'skördbar fortlöpande'],
  },
  {
    slug: 'spinach',
    name: 'Spinach',
    nameSv: 'Spenat',
    family: 'Amaranthaceae',
    plantsPerSquare: 9,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 40,
    description: 'Näringsrikt blad för sval säsong. Skjuter snabbt i värme — så tidigt på våren eller på hösten.',
    tips: 'Håll jorden fuktig. Täckodla för att hålla rötterna svala.',
    emoji: '🌱',
    tags: ['grönsak', 'sval säsong', 'skördbar fortlöpande'],
  },
  {
    slug: 'radish',
    name: 'Radish',
    nameSv: 'Rädisa',
    family: 'Brassicaceae',
    plantsPerSquare: 16,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 25,
    description: 'Trädgårdens snabbaste grönsak. Markerar långsamt grobara rader och luckrar packad jord.',
    tips: 'Skörda i tid — annars blir de träiga och starka. Bra som radmarkör.',
    emoji: '🌰',
    tags: ['grönsak', 'rotfrukt', 'sval säsong', 'snabb'],
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    nameSv: 'Gurka',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 55,
    description: 'Produktiv klättrare för varma lägen. Led upp på spaljé för att spara plats. Skörda ofta för fortsatt skörd.',
    tips: 'Låt aldrig jorden torka ut, annars blir frukten besk. Plocka medan de är fasta.',
    emoji: '🥒',
    tags: ['grönsak', 'värmekrävande', 'spaljé'],
  },
  {
    slug: 'zucchini',
    name: 'Zucchini',
    nameSv: 'Zucchini',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 50,
    description: 'Extremt produktiv sommarsquash. En planta räcker ofta åt en hel familj. Skörda när de är 15–20 cm långa.',
    tips: 'Handpollinera om frukterna trillar av tidigt. Ta bort övermogna frukter direkt.',
    emoji: '🫑',
    tags: ['grönsak', 'värmekrävande', 'rikbärande'],
  },
  {
    slug: 'peas',
    name: 'Peas',
    nameSv: 'Ärtor',
    family: 'Fabaceae',
    plantsPerSquare: 8,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 60,
    description: 'Baljväxt för sval säsong som kvävefixerar jorden. Behöver stöd att klättra på.',
    tips: 'Så så fort jorden kan bearbetas. Missfärgade baljor betyder övermogna ärtor.',
    emoji: '🫛',
    tags: ['grönsak', 'baljväxt', 'sval säsong', 'kvävefixerare'],
  },
  {
    slug: 'green-beans',
    name: 'Green Beans',
    nameSv: 'Bönor',
    family: 'Fabaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 55,
    description: 'Baljväxt för varm säsong. Buskbönor klarar sig utan stöd; störbönor klättrar och producerar längre.',
    tips: 'Direktså efter sista frosten. Undvik vattning uppifrån för att förebygga sjukdomar.',
    emoji: '🫘',
    tags: ['grönsak', 'baljväxt', 'värmekrävande', 'kvävefixerare'],
  },
  {
    slug: 'broccoli',
    name: 'Broccoli',
    nameSv: 'Broccoli',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 80,
    description: 'Korsblommig för sval säsong. Förkultivera tidigt. Skörda huvudet innan det blommar, sidoskotten kommer sedan.',
    tips: 'Jämn fuktighet förhindrar ihåliga stjälkar. Täck med fiberduk mot kålfjärilar.',
    emoji: '🥦',
    tags: ['grönsak', 'kålväxt', 'sval säsong'],
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    nameSv: 'Kål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 90,
    description: 'Stor kålväxt som upptar en hel ruta. Storkrävare — behöver näringsrik jord.',
    tips: 'Tryck till jorden runt basen så plantan inte välter. Huvudena spricker vid ojämn vattning.',
    emoji: '🥬',
    tags: ['grönsak', 'kålväxt', 'sval säsong'],
  },
  {
    slug: 'kale',
    name: 'Kale',
    nameSv: 'Grönkål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 55,
    description: 'Härdig kålväxt som blir bättre efter frost. Plocka ytterbladen, plantan fortsätter producera hela säsongen.',
    tips: 'Sötare efter en frostig natt. Perfekt för höstskördar.',
    emoji: '🌿',
    tags: ['grönsak', 'kålväxt', 'sval säsong', 'härdig'],
  },
  {
    slug: 'beet',
    name: 'Beetroot',
    nameSv: 'Rödbeta',
    family: 'Amaranthaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 60,
    description: 'Två-i-ett: ät rötterna och använd blasten som grönsak. Mycket frosttålig.',
    tips: 'Varje frökapsel innehåller 2–3 frön — gallra till en planta per ställe.',
    emoji: '🔴',
    tags: ['grönsak', 'rotfrukt', 'sval säsong'],
  },
  {
    slug: 'potato',
    name: 'Potato',
    nameSv: 'Potatis',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 80,
    description: 'Platskrävande knöl. Sätt certifierad sättpotatis för att undvika sjukdomar. Kupa jord när bladen växer.',
    tips: 'Kupa när plantorna är 15 cm höga för ökad skörd. Sluta vattna när blasten dör.',
    emoji: '🥔',
    tags: ['grönsak', 'knöl', 'värmekrävande'],
  },
  {
    slug: 'leek',
    name: 'Leek',
    nameSv: 'Purjolök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 120,
    description: 'Långsamväxande lökväxt med mild smak. Bleker stjälken genom att kupa jord runt den.',
    tips: 'Förkultivera tidigt — behöver 8–10 veckor innan plantering.',
    emoji: '🌿',
    tags: ['grönsak', 'lökväxt', 'sval säsong'],
  },
  {
    slug: 'parsley',
    name: 'Parsley',
    nameSv: 'Persilja',
    family: 'Apiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 70,
    description: 'Tvåårig ört som odlas som ettårig. Långsam grobarhet — blötlägg fröna över natten innan sådd.',
    tips: 'Skär av hela stjälkar från ytterkanten. Lockar nyttoinsekter.',
    emoji: '🌿',
    tags: ['ört', 'sval säsong'],
  },
  {
    slug: 'dill',
    name: 'Dill',
    nameSv: 'Dill',
    family: 'Apiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 40,
    description: 'Snabbväxande ört med fjäderlika blad. Bra till inläggning och fiskrätter.',
    tips: 'Direktså på platsen — dill gillar inte att flyttas. Låt några gå i frö för nästa år.',
    emoji: '🌿',
    tags: ['ört', 'sval säsong', 'lockar nyttoinsekter'],
  },
  {
    slug: 'marigold',
    name: 'Marigold',
    nameSv: 'Ringblomma',
    family: 'Asteraceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 50,
    description: 'Blommor som skyddar hela odlingen. Skrämmer bort nematoder, bladlöss och vita flygare. Plantera längs kanterna.',
    tips: 'Plocka bort utblommade blommor så fortsätter den blomma hela säsongen.',
    emoji: '🌼',
    tags: ['blomma', 'sällskapsväxt', 'skadedjursskydd'],
  },
  {
    slug: 'pepper',
    name: 'Bell Pepper',
    nameSv: 'Paprika',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 75,
    description: 'Värmekrävande planta med lång säsong. Förkultivera 8–10 veckor före sista frosten. Behöver värme för att producera.',
    tips: 'Låt paprikorna mogna fullt för sötaste smak. Jämn vattning förhindrar blomtapp.',
    emoji: '🫑',
    tags: ['grönsak', 'värmekrävande'],
  },
  {
    slug: 'cauliflower',
    name: 'Cauliflower',
    nameSv: 'Blomkål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 80,
    description: 'Krävande kålväxt som behöver jämna förhållanden. Blekt huvud genom att vika bladen över det.',
    tips: 'Undvik värmestress — fördröjer blomkålsbildningen. Mycket känslig för ojämn vattning.',
    emoji: '🥦',
    tags: ['grönsak', 'kålväxt', 'sval säsong'],
  },
  {
    slug: 'swiss-chard',
    name: 'Swiss Chard',
    nameSv: 'Mangold',
    family: 'Amaranthaceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 50,
    description: 'Färggrann och produktiv. Klarar värme bättre än spenat. Skörda fortlöpande.',
    tips: 'Skörda ytterstjälkarna; innerbladen fortsätter växa hela säsongen.',
    emoji: '🌈',
    tags: ['grönsak', 'sval säsong', 'skördbar fortlöpande'],
  },
  {
    slug: 'pumpkin',
    name: 'Pumpkin',
    nameSv: 'Pumpa',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 100,
    description: 'Stor revande planta — behöver 2–4 m² att breda ut sig på. Skörda efter första frosten när skalet är hårt.',
    tips: 'Lägg frukten på en sten eller bricka för att förhindra röta. Led revorna med stickor.',
    emoji: '🎃',
    tags: ['grönsak', 'värmekrävande', 'revande'],
  },
];

export function getPlant(slug: string): Plant | undefined {
  return PLANTS.find((p) => p.slug === slug);
}

export const SUN_LABELS: Record<SunRequirement, string> = {
  full: 'Full sol',
  partial: 'Halvskugga',
  shade: 'Skugga',
};

export const WATER_LABELS: Record<WaterRequirement, string> = {
  low: 'Låg',
  medium: 'Medel',
  high: 'Hög',
};

export const SUN_ICONS: Record<SunRequirement, string> = {
  full: '☀️',
  partial: '⛅',
  shade: '🌥️',
};

export const WATER_ICONS: Record<WaterRequirement, string> = {
  low: '💧',
  medium: '💧💧',
  high: '💧💧💧',
};
