export type SunRequirement = 'full' | 'partial' | 'shade';
export type WaterRequirement = 'low' | 'medium' | 'high';

export interface Plant {
  slug: string;
  name: string;
  nameSv: string;
  family: string;
  plantsPerSquare: number; // how many fit in one 30x30cm square
  sunRequirement: SunRequirement;
  waterRequirement: WaterRequirement;
  daysToHarvest: number;
  description: string;
  tips: string;
  emoji: string;
  tags: string[];
}

export const PLANTS: Plant[] = [
  {
    slug: 'tomato',
    name: 'Tomato',
    nameSv: 'Tomat',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 70,
    description: 'The garden staple. Needs full sun and consistent watering. Stake or cage to support growth.',
    tips: 'Pinch off suckers for larger fruit. Water deeply but infrequently.',
    emoji: '🍅',
    tags: ['vegetable', 'warm-season', 'staking'],
  },
  {
    slug: 'basil',
    name: 'Basil',
    nameSv: 'Basilika',
    family: 'Lamiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 25,
    description: 'Aromatic herb that thrives in warm conditions. Great for companion planting with tomatoes.',
    tips: 'Pinch flower buds to keep leaves coming. Harvest in the morning for best flavor.',
    emoji: '🌿',
    tags: ['herb', 'warm-season'],
  },
  {
    slug: 'carrot',
    name: 'Carrot',
    nameSv: 'Morot',
    family: 'Apiaceae',
    plantsPerSquare: 16,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 75,
    description: 'Crunchy root vegetable. Direct sow in deep, loose soil. Thin to 5 cm apart.',
    tips: 'Loosen soil to 30 cm deep. Avoid fresh manure — causes forked roots.',
    emoji: '🥕',
    tags: ['vegetable', 'root', 'cool-season'],
  },
  {
    slug: 'onion',
    name: 'Onion',
    nameSv: 'Lök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 100,
    description: 'Long-season bulb vegetable. Plant sets or transplants in early spring.',
    tips: 'Leaves falling over signals maturity. Cure in a dry spot for 2–3 weeks before storing.',
    emoji: '🧅',
    tags: ['vegetable', 'bulb', 'cool-season'],
  },
  {
    slug: 'garlic',
    name: 'Garlic',
    nameSv: 'Vitlök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 240,
    description: 'Plant cloves in autumn for a summer harvest. Excellent natural pest deterrent.',
    tips: 'Break scape off when it curls to direct energy to the bulb. Harvest when half the leaves are brown.',
    emoji: '🧄',
    tags: ['vegetable', 'bulb', 'overwintering'],
  },
  {
    slug: 'lettuce',
    name: 'Lettuce',
    nameSv: 'Sallat',
    family: 'Asteraceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 45,
    description: 'Fast-growing salad green. Tolerates light shade and cool weather. Bolt-resistant varieties last longer.',
    tips: 'Cut outer leaves and the plant keeps producing. Succession-sow every 2 weeks.',
    emoji: '🥬',
    tags: ['vegetable', 'cool-season', 'cut-and-come-again'],
  },
  {
    slug: 'spinach',
    name: 'Spinach',
    nameSv: 'Spenat',
    family: 'Amaranthaceae',
    plantsPerSquare: 9,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 40,
    description: 'Nutrient-dense cool-season green. Bolts quickly in heat — sow in early spring or autumn.',
    tips: 'Keep soil moist. Mulch to retain moisture and keep roots cool.',
    emoji: '🌱',
    tags: ['vegetable', 'cool-season', 'cut-and-come-again'],
  },
  {
    slug: 'radish',
    name: 'Radish',
    nameSv: 'Rädisa',
    family: 'Brassicaceae',
    plantsPerSquare: 16,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 25,
    description: 'Fastest vegetable in the garden. Marks slow-germinating rows and breaks up compacted soil.',
    tips: 'Harvest promptly — left too long they become woody and hot. Great row marker.',
    emoji: '🌰',
    tags: ['vegetable', 'root', 'cool-season', 'quick'],
  },
  {
    slug: 'cucumber',
    name: 'Cucumber',
    nameSv: 'Gurka',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 55,
    description: 'Prolific warm-season vine. Train up a trellis to save space. Harvest frequently to keep producing.',
    tips: 'Never let the soil dry out or fruit will taste bitter. Pick while still firm.',
    emoji: '🥒',
    tags: ['vegetable', 'warm-season', 'trellis'],
  },
  {
    slug: 'zucchini',
    name: 'Zucchini',
    nameSv: 'Zucchini',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 50,
    description: 'Extremely productive summer squash. One plant often feeds a family. Harvest when 15–20 cm long.',
    tips: 'Hand-pollinate if fruit drops off early. Remove oversized fruit promptly.',
    emoji: '🫑',
    tags: ['vegetable', 'warm-season', 'prolific'],
  },
  {
    slug: 'peas',
    name: 'Peas',
    nameSv: 'Ärtor',
    family: 'Fabaceae',
    plantsPerSquare: 8,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 60,
    description: 'Cool-season legume that fixes nitrogen in the soil. Needs support to climb.',
    tips: 'Sow as early as soil can be worked. Pod discoloration means they\'re overripe.',
    emoji: '🫛',
    tags: ['vegetable', 'legume', 'cool-season', 'nitrogen-fixer'],
  },
  {
    slug: 'green-beans',
    name: 'Green Beans',
    nameSv: 'Bönor',
    family: 'Fabaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 55,
    description: 'Warm-season legume. Bush types need no staking; pole types climb and produce longer.',
    tips: 'Direct sow after last frost. Avoid overhead watering to prevent disease.',
    emoji: '🫘',
    tags: ['vegetable', 'legume', 'warm-season', 'nitrogen-fixer'],
  },
  {
    slug: 'broccoli',
    name: 'Broccoli',
    nameSv: 'Broccoli',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 80,
    description: 'Cool-season brassica. Start early indoors. Harvest the central head before it flowers, then side shoots follow.',
    tips: 'Consistent moisture prevents hollow stems. Cover with row fabric to deter cabbage moths.',
    emoji: '🥦',
    tags: ['vegetable', 'brassica', 'cool-season'],
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    nameSv: 'Kål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 90,
    description: 'Large brassica that takes up a full square. Heavy feeder — needs rich soil.',
    tips: 'Firm soil around the base to prevent tipping. Heads split if watered irregularly.',
    emoji: '🥬',
    tags: ['vegetable', 'brassica', 'cool-season'],
  },
  {
    slug: 'kale',
    name: 'Kale',
    nameSv: 'Grönkål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 55,
    description: 'Hardy brassica that improves after frost. Pick outer leaves; plant continues producing all season.',
    tips: 'Sweetens after a hard frost. Great for autumn harvests.',
    emoji: '🌿',
    tags: ['vegetable', 'brassica', 'cool-season', 'hardy'],
  },
  {
    slug: 'beet',
    name: 'Beetroot',
    nameSv: 'Rödbeta',
    family: 'Amaranthaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 60,
    description: 'Dual-purpose plant: enjoy the roots and use the tops as greens. Very cold-tolerant.',
    tips: 'Each seed cluster contains 2–3 seeds — thin to one seedling per spot.',
    emoji: '🔴',
    tags: ['vegetable', 'root', 'cool-season'],
  },
  {
    slug: 'potato',
    name: 'Potato',
    nameSv: 'Potatis',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 80,
    description: 'Space-hungry tuber. Plant certified seed potatoes to avoid disease. Mound soil as haulm grows.',
    tips: 'Hill up soil when plants are 15 cm tall to increase yield. Stop watering when tops die back.',
    emoji: '🥔',
    tags: ['vegetable', 'tuber', 'warm-season'],
  },
  {
    slug: 'leek',
    name: 'Leek',
    nameSv: 'Purjolök',
    family: 'Amaryllidaceae',
    plantsPerSquare: 9,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 120,
    description: 'Long-season allium with mild flavor. Blanch the stem by mounding soil as it grows.',
    tips: 'Start indoors early — needs 8–10 weeks before transplanting.',
    emoji: '🌿',
    tags: ['vegetable', 'allium', 'cool-season'],
  },
  {
    slug: 'parsley',
    name: 'Parsley',
    nameSv: 'Persilja',
    family: 'Apiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 70,
    description: 'Biennial herb grown as annual. Slow germination — soak seeds overnight before sowing.',
    tips: 'Cut whole stems from the outside. Attracts beneficial insects.',
    emoji: '🌿',
    tags: ['herb', 'cool-season'],
  },
  {
    slug: 'dill',
    name: 'Dill',
    nameSv: 'Dill',
    family: 'Apiaceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 40,
    description: 'Fast-growing herb with feathery leaves. Great for pickling and fish dishes.',
    tips: 'Direct sow in place — dill dislikes transplanting. Let some bolt to seed for next year.',
    emoji: '🌿',
    tags: ['herb', 'cool-season', 'attracts-beneficials'],
  },
  {
    slug: 'marigold',
    name: 'Marigold',
    nameSv: 'Ringblomma',
    family: 'Asteraceae',
    plantsPerSquare: 4,
    sunRequirement: 'full',
    waterRequirement: 'low',
    daysToHarvest: 50,
    description: 'Flowers that protect the whole garden. Repels nematodes, aphids, and whiteflies. Edge beds with them.',
    tips: 'Deadhead spent flowers to keep blooming all season.',
    emoji: '🌼',
    tags: ['flower', 'companion', 'pest-repellent'],
  },
  {
    slug: 'pepper',
    name: 'Bell Pepper',
    nameSv: 'Paprika',
    family: 'Solanaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'medium',
    daysToHarvest: 75,
    description: 'Long-season warm crop. Start indoors 8–10 weeks before last frost. Needs heat to produce well.',
    tips: 'Allow peppers to fully ripen for sweetest flavor. Consistent watering prevents blossom drop.',
    emoji: '🫑',
    tags: ['vegetable', 'warm-season'],
  },
  {
    slug: 'cauliflower',
    name: 'Cauliflower',
    nameSv: 'Blomkål',
    family: 'Brassicaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 80,
    description: 'Demanding brassica that needs consistent conditions. Blanch the head by tying leaves over it.',
    tips: 'Avoid heat stress — delay heading. Very sensitive to inconsistent watering.',
    emoji: '🥦',
    tags: ['vegetable', 'brassica', 'cool-season'],
  },
  {
    slug: 'swiss-chard',
    name: 'Swiss Chard',
    nameSv: 'Mangold',
    family: 'Amaranthaceae',
    plantsPerSquare: 4,
    sunRequirement: 'partial',
    waterRequirement: 'medium',
    daysToHarvest: 50,
    description: 'Colorful and productive. Tolerates heat better than spinach. Cut-and-come-again harvesting.',
    tips: 'Harvest outer stalks; inner leaves will keep growing all season.',
    emoji: '🌈',
    tags: ['vegetable', 'cool-season', 'cut-and-come-again'],
  },
  {
    slug: 'pumpkin',
    name: 'Pumpkin',
    nameSv: 'Pumpa',
    family: 'Cucurbitaceae',
    plantsPerSquare: 1,
    sunRequirement: 'full',
    waterRequirement: 'high',
    daysToHarvest: 100,
    description: 'Large spreading vine — needs 2–4 m² to roam. Harvest after first frost when rind is hard.',
    tips: 'Elevate fruit on a tile to prevent rot. Train vines with stakes.',
    emoji: '🎃',
    tags: ['vegetable', 'warm-season', 'sprawling'],
  },
];

export function getPlant(slug: string): Plant | undefined {
  return PLANTS.find((p) => p.slug === slug);
}

export const SUN_LABELS: Record<SunRequirement, string> = {
  full: 'Full sun',
  partial: 'Partial sun',
  shade: 'Shade',
};

export const WATER_LABELS: Record<WaterRequirement, string> = {
  low: 'Low',
  medium: 'Medium',
  high: 'High',
};

export const SUN_ICONS: Record<SunRequirement, string> = {
  full: '☀️',
  partial: '⛅',
  shade: '🌥️',
};

export const WATER_ICONS: Record<WaterRequirement, string> = {
  low: '💧',
  medium: '💧💧',
  high: '💧💧💧',
};
