// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --esm prisma/seed.ts",
  },
  datasource: {
    // Use direct connection for schema operations (db push, migrate) — pooler doesn't support DDL
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
